apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-app/helm/postgres-cluster
    repoURL: git@github.com:fabriziowho/webapp-project.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
