frontend:
  image:
    repository: fabriziowho/fullstack-webapi-k8s
    tag: frontend
    pullPolicy: IfNotPresent
  service:
    port: 80

webapp:
  image:
    repository: fabriziowho/fullstack-webapi-k8s
    tag: api-webapp
    pullPolicy: IfNotPresent
  service:
    port: 5000

postgresql:
  image:
    repository: postgres
    tag: "13"
  secretRefName: postgres-cluster-pguser-postgres-cluster
  service:
    port: 5432
